export const checkBoxFormLayout = [1, 2, 1];
export const checkBoxFormFields = {
  // acknowledgement: {
  //   fieldType: "checkbox",
  //   label: "I acknowledge that this patient.",
  //   value: false,
  //   row: 1,
  //   col: 1,
  // },
  // firstname: {
  //   fieldType: "text",
  //   label: "First Name",
  //   value: "jo an jane",
  //   row: 2,
  //   col: 1,
  // },

  // firstname: {
  //   fieldType: "text",
  //   label: "First Name",
  //   value: "jo an jane",
  //   row: 2,
  //   col: 1,
  // },
  // options: {
  //   fieldType: "multioptions",
  //   label: "Options",
  //   value: [],
  //   row: 2,
  //   col: 1,
  // },
  countries: {
    fieldType: "select",
    label: "Countries",
    value: [],
    isSelectAll: true,
    selectOptions: [],
    fieldconfig: { multiple: true },
    row: 1,
    col: 1,
  },
  sitePreferenceQuestion: {
    fieldType: "richTextEditor",
    label: "Site Preference Question",
    initialValue: "",
    row: 1,
    col: 1,
  },
  // middleintial: {
  //   fieldType: "text",
  //   label: "Middle Initial",
  //   value: "jo an jane",
  //   row: 2,
  //   col: 1,
  // },
  // lastname: {
  //   fieldType: "text",
  //   label: "Last Name",
  //   value: "jo an jane",
  //   row: 2,
  //   col: 1,
  // },
  // preferredlanguageId: {
  //   fieldType: "select",
  //   label: "Preferred Language",
  //   value: 2,
  //   selectOptions: [{ id: 2, displayText: "English" }],
  //   row: 2,
  //   col: 1,
  // },
  // emailAddress: {
  //   fieldType: "text",
  //   label: "Email Address",
  //   value: "jo an jane",
  //   row: 2,
  //   col: 1,
  // },
  // emailAddressConfirmation: {
  //   fieldType: "text",
  //   label: "Confirm Email Address",
  //   value: "jo an jane",
  //   row: 2,
  //   col: 1,
  // },
  // // gender: {
  // //   fieldType: "radio",
  // //   label: "Gender",
  // //   value: "jo an jane",
  // //   selectOptions: [
  // //     { label: "Male", value: "male" },
  // //     { label: "Female", value: "female" },
  // //   ],
  // //   row: 2,
  // //   col: 1,
  // // },
  // dateOfBirth: {
  //   fieldType: "date",
  //   label: "Date Of Birth",
  //   value: "2020-08-23",
  //   row: 2,
  //   col: 2,
  // },
  // countryId: {
  //   fieldType: "select",
  //   label: "Country",
  //   value: 784,
  //   selectOptions: [{ id: 784, displayText: "United States" }],
  //   row: 2,
  //   col: 2,
  // },
  // stateId: {
  //   fieldType: "select",
  //   label: "State",
  //   value: 2341,
  //   selectOptions: [{ id: 2341, displayText: "Masachusetts" }],
  //   row: 2,
  //   col: 2,
  // },
  // sourceId: {
  //   fieldType: "select",
  //   label: "Source",
  //   value: 1,
  //   selectOptions: [{ id: 1, displayText: "Referral" }],
  //   row: 2,
  //   col: 2,
  // },
  // participationProgressId: {
  //   fieldType: "select",
  //   label: "Participation Progress",
  //   value: 2,
  //   selectOptions: [{ id: 2, displayText: "Consented" }],
  //   row: 2,
  //   col: 2,
  // },
  // patientIXRSId: {
  //   fieldType: "select",
  //   label: "Subject",
  //   value: 14,
  //   selectOptions: [{ id: 14, displayText: "100-508" }],
  //   row: 2,
  //   col: 2,
  // },
  // acknowledgement: {
  //   fieldType: "checkbox",
  //   label:
  //     "I acknowledge that this patient understands that I will be sharing their contact/personal information in the TCN System for the sole purpose of providing and managing support services. At any time, they may request, through the site staff, to view, change, or delete their personally identifiable information. Should this occur, site staff will transfer this request via TCN Study Messages, for appropriate action and response.",
  //   value: false,
  //   row: 3,
  //   col: 1,
  // },
};
