export const myFormLayout = [2];
export const myFormFields = {
  // "Select all that apply": {
  //   fieldType: "checkboxgroup",
  //   label: "Select all that apply",
  //   value: "",
  //   selectOptions: [
  //     {
  //       id: 236260,
  //       displayText: "today is a weekday",
  //     },
  //     {
  //       id: 366442,
  //       displayText: "today is holiday",
  //     },
  //   ],
  //   row: 1,
  //   col: 1,
  // },

  acknowledgement: {
    fieldType: "checkbox",
    label:
      "I acknowledge that this patient understands that I will be sharing their contact/personal information in the TCN System for the sole purpose of providing and managing support services. At any time, they may request, through the site staff, to view, change, or delete their personally identifiable information. Should this occur, site staff will transfer this request via TCN Study Messages, for appropriate action and response.",
    value: false,
    row: 1,
    col: 1,
  },
  firstname: {
    fieldType: "text",
    label: "First Name",
    value: "",
    row: 2,
    col: 1,
  },
  middleintial: {
    fieldType: "text",
    label: "Middle Initial",
    value: "",
    row: 2,
    col: 1,
  },
  lastname: {
    fieldType: "text",
    label: "Last Name",
    value: "",
    row: 2,
    col: 1,
  },
  preferredlanguageId: {
    fieldType: "select",
    label: "Preferred Language",
    value: -1,
    selectOptions: [],
    row: 2,
    col: 1,
  },
  emailAddress: {
    fieldType: "text",
    label: "Email Address",
    value: "",
    row: 2,
    col: 1,
  },
  emailAddressConfirmation: {
    fieldType: "text",
    label: "Confirm Email Address",
    value: "",
    row: 2,
    col: 1,
  },
  // gender: {
  //   fieldType: "radio",
  //   label: "Gender",
  //   value: "",
  //   selectOptions: [
  //     { label: "Male", value: "male" },
  //     { label: "Female", value: "female" },
  //   ],
  //   row: 2,
  //   col: 1,
  // },
  dateOfBirth: {
    fieldType: "date",
    label: "Date Of Birth",
    value: "",
    row: 2,
    col: 2,
  },
  countryId: {
    fieldType: "select",
    label: "Country",
    value: -1,
    selectOptions: [],
    row: 2,
    col: 2,
  },
  stateId: {
    fieldType: "select",
    label: "State",
    value: -1,
    selectOptions: [],
    row: 2,
    col: 2,
  },
  sourceId: {
    fieldType: "select",
    label: "Source",
    value: -1,
    selectOptions: [{ label: "dummy", value: 1 }],
    row: 2,
    col: 2,
  },
  participationProgressId: {
    fieldType: "select",
    label: "Participation Progress",
    value: -1,
    selectOptions: [],
    row: 2,
    col: 2,
  },
  patientIXRSId: {
    fieldType: "select",
    label: "Subject",
    value: -1,
    selectOptions: [],
    row: 2,
    col: 2,
  },
};
